### ISSUE TITLE
Fix CAA Violations data issue

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#100]
When I run Cross-Programs.ipynb for CAA Violations I get in an error in cell 10, the chart-making cell. That's because it can't aggregate the data. It is looking for a column "Date" to aggregate the data by (program.agg_col) but this hasn't been created. Date should be a combination of HPV_DAYZERO_DATE and FRV_DATE (See DataSetResults.py), but for some reason that isn't being called in Cross-Programs.ipynb even though it is called in AllPrograms.ipynb.

**Comment by shansen5** [comment]
The DataSetResults.py was added for AllPrograms, with the intent to also use it in CrossPrograms when I got back to working on that notebook.  (Which is anon.)
