### ISSUE TITLE
DFR links

### ISSUE THREAD

**Issue by leiffredrickson** [edgi-govdata-archiving/ECHO-Cross-Program#102]
For CAA violations, step 12 generates a list of what looks like links to detailed facility report, but they all go here: https://echo.epa.gov/detailed-facility-report?f. If the intention is not to click on these links (but just generate the downloadable spreadsheet of information) -- then no worries. But thought I would flag this in case the intention was to get a detailed facility report. (When you click on the links to DFRs in the map it does take you to the DFR for that facility). 

This happens with other subprograms besides CAA violations, too.

**Comment by ericnost** [comment]
FYI same as #82

**Comment by shansen5** [comment]
Fixed in enhancements-09-11 branch and merged into master.
