### ISSUE TITLE
CAA enforcements issue

### ISSUE THREAD

**Issue by leiffredrickson** [edgi-govdata-archiving/ECHO-Cross-Program#103]
It appears that CAA enforcements actions is not drawing from ICIS-AIR_FORMAL_ACTIONS. Based on column headings, looks like it's drawing from an FE&C csv called CASE_ENFORCEMENTS and using the column "Fiscal_Year" to generate enforcements counts by year. For Wayne County, there are only enforcement actions for 2001 and 2002. I'm not entirely clear what the CASE_ENFORCEMENTS.csv is. But anyway - I think this is probably producing a serious error.

**Comment by shansen5** [comment]
We have CAA Penalties that is using the ICIS-AIR_FORMAL_ACTIONS.  We didn't use CAA Enforcements in AllPrograms, and I'll remove it from the data sets available in CrossPrograms.
