### ISSUE TITLE
add note to each of the report card ipynb re how results may vary

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#107]
Because the report card data was generated from a run in mid-late September, some of the values will vary. That's because of: 1) the past 12/13 quarters are different; 2) data from earlier in 2020 for those past 12/13 quarters may have been updated; 3) our "active facilities" calculation - for 2019 rates - is based on the FAC_ACTIVE_FLAG that is actually a "right now" determination on EPA's part.

Applies to AllPrograms and ECHO_National.

**Comment by ericnost** [comment]
The note should essentially say this:

This notebook pulls data from a copy of EPA's ECHO database hosted by Stony Brook University. The data sets are updated on a weekly basis, meaning that some of the results from your run may not exactly match those in EEW's Congressional Report Cards. For instance, for each program, the Report Cards show ten facilities that have spent at least three of the past 12 (and for CWA, 13) quarters in non-compliance. These results will therefore change as we enter new parts of the year. In addition, the Report Cards _estimate_ the number of facilities that were active in 2019, since EPA does not provide such figures. Our estimate is based on the number of facilities EPA records as active _at the current moment in time._ In short, we use active right now (in Fall 2020) as a proxy for active in 2019. This number informs several metrics in the Report Cards - including violations and inspections per 1000 facilities - and these will change as the number of facilities reported as "active" right now by the EPA changes. Please see the CD-Report repo for facility counts and non-compliance rates as we recorded them in mid-September 2020 in order to produce the Report Cards.

**Comment by shansen5** [comment]
This note was added into the AllPrograms and ECHO-Cross-Programs notebooks.
