### ISSUE TITLE
add link to EEW website and report cards in readme

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#108]
Will this be the right URL @Frijol? ~https://www.environmentalenforcementwatch.org/cd-reports/~

Right URL: environmentalenforcementwatch.org/reports

**Comment by Frijol** [comment]
No, it will be environmentalenforcementwatch.org/reports

**Comment by shansen5** [comment]
Added a link there, but need to verify when the site is active.

**Comment by Frijol** [comment]
Go ahead!

**Comment by ericnost** [comment]
Verified!
