### ISSUE TITLE
add github link in ECHO-National-092420.ipynb notebook

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/ECHO-Cross-Program#111]
Noticed the link to github is missing in the header of this notebook:
https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-Cross-Program/blob/master/ECHO_National.ipynb

**Comment by shansen5** [comment]
The Cross-Programs and AllPrograms notebooks were both pointing to the COVID notebook repo:
#### This notebook is licensed under GPL 3.0. Please visit our Github repo for more information: https://github.com/edgi-govdata-archiving/ECHO-COVID19
...while the National didn't link to any.  Corrected all 3.
