### ISSUE TITLE
Add Discharge Monitoring Reports (DMR) as a data set in ECHO-Cross-Program

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO-Cross-Program#145]
There is a "DMRs" data set defined in ECHO_modules.data_set_presets, but we aren't bringing it into ECHO-Cross-Program.  It may take some special handling.  It should probably be renamed Discharge Monitoring, since that is more descriptive.
Currently adding it to the data set list does not work.  (See the ECHO-Watershed notebook for how it handles this data.)

**Comment by ericnost** [comment]
I think we do this now!
