### ISSUE TITLE
Move DataSet class to external file

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO-Cross-Program#19]
Move the class out of the notebook to an external DataSet.py file.  It must also work in Google Colab.

**Comment by ericnost** [comment]
I think this is a very important issue to consider and may greatly change how we develop the notebooks going forward - for the better. 

A core goal of EEW is to open up the "black box" of EPA data and its analysis. That's why we've turned to Jupyter Notebooks, which expose both the ECHO database itself as well as the code we use to make sense of the data.

But, the more functionality we add - the more ability we give to users to interact with ECHO in meaningful ways - the more code we have to write. Big blocks of code may dissuade some people from engaging. This was already mentioned in one of Chris's student surveys.

With something like this, we can hide the less meaningful and interactive parts of the code, without, of course, black-boxing everything.

**Comment by ericnost** [comment]
From a technical perspective, here's one way this can be done:

See here: https://stackoverflow.com/a/49452931

The answer given in 2. is not entirely correct, but here is 
a test implementation: https://colab.research.google.com/drive/12GiLKC_CCIcfgW0-UAQL65bU-hr3dFxc?usp=sharing This Colab notebook copies a Github repo of mine into the user's Drive workspace, and then `%run` the external .py file, whose functions are then made available within the notebook.

This could provide one way to standardize and modularize our code moving forward - again, in ways that do not close back up the black box. I could see modules for DB queries, charts, and maps, where possible.

One idea is that we could create a repo to store these modules, e.g. ECHO-modules, cloning the repo into each Notebook and running only those modules needed.

**Comment by Frijol** [comment]
I'm interested in the modularization question in general, wondering if we can have markdown modules as well for templating purposes/not repeating ourselves when we write blanket copy

**Comment by shansen5** [comment]
It works fine to put the DataSet class in ECHO-Modules and then have a cell do this to bring that github module into the google colab session:
`!git clone https://github.com/edgi-govdata-archiving/ECHO-modules.git`
Doing that, we need to load the class into our notebook that uses it, which I am doing by this magic:
`%load DataSet.py`
That works, but it brings all of the code from DataSet.py into the cell, so from the perspective of reducing the volume of code in the cells that the user has to see it doesn't save anything.  It does still have the benefit of modularizing the code, so the DataSet class can be used in other notebooks.

**Comment by ericnost** [comment]
I have been testing this out and here is what I've found:

In local notebooks, `%load ECHO-modules/DataSet.py` will indeed just load the code into the cell. Yes - it is not helpful from the perspective of reducing volume, but it does modularize. 

In local notebooks, `%run ECHO-modules/DataSet.py` will load the code as if it were importing a module, without loading the code into the cell. Everything works fine - the data sets can be initialized using the Data_Set class. However, at this point in the main script `program_data = program.get_data( ee_ids=registry_ids )`, I get the following error: `NameError: name 'get_data' is not defined` and also `NameError: name 'pd' is not defined` 

On Colab, I can `%load ECHO-modules/DataSet.py` without the code loading in the cell, but face the same errors at `program_data = program.get_data( ee_ids=registry_ids )`

On Colab, I can avoid magic with:

```
import sys
sys.path.append('ECHO-modules')
from DataSet import *
```

But run into the same errors.

**Comment by shansen5** [comment]
It works if we also move the global get_data() function (and its required imports) into DataSet.py.

Try this one:  https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-Cross-Program/blob/external-python/facility-all-programs.ipynb#scrollTo=5ZlPYAqadRcs
