### ISSUE TITLE
Congressional District selection does not work as intended

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#30]
There is an error when selecting a CD.

The error is here:

```
echo_data_sql = "select * from ECHO_EXPORTER where " + region_field[selected_region_type]['field']
echo_data_sql += " like \'" + str( region_selected) + "%\'"
```

Using `like` means that we grab too much data. For instance, if you wanted to look at NY-1, it will actually give you NY-1 and all other NY CDs that have a 1 in them.

I believe `like` is useful for zips and counties (especially with the Alameda vs Alameda County issue) but is not helpful for CDs.

**Comment by shansen5** [comment]
Fixed in the 'bug-fixes' branch.

**Comment by ericnost** [comment]
@shansen5 Thanks! But I'm looking at the bug-fixes branch here and I'm running in to the same problem: https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-Cross-Program/blob/bug-fixes/facility-all-programs.ipynb

**Comment by ericnost** [comment]
I committed a minor change to bug-fixes to temporarily fix this, so others can run the Cross-Program notebook for a Congressional District today

**Comment by saraannwylie** [comment]
just a bravo!
