### ISSUE TITLE
Air inspections data does not load

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#31]
In the cell that begins `program = data_sets[ data_set_widget.value ]` ...., I am unable to load Air inspections data (for NY-1 at least). Surely there must be inspections....

**Comment by ericnost** [comment]
To clarify, the cell block resolves, but then in the "Chart This" block below, I receive the following message: "There's no data to chart for Air Inspections !" Again, there must be inspections!

**Comment by ericnost** [comment]
The CAA inspections notebook reports 3 violations in NY-1.

**Comment by ericnost** [comment]
In addition, I cannot load Air Violations or Air Formal Actions (for NY-1). For both of those datasets, I receive the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-21-9e09092fd9df> in <module>()
     18     program_data = program.get_data( ee_ids=registry_ids )
     19 else:
---> 20     program_data = program.get_data( ee_ids=ids )
     21 
     22 program_data

3 frames
/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in set_index(self, keys, drop, append, inplace, verify_integrity)
   4301 
   4302         if missing:
-> 4303             raise KeyError(f"None of {missing} are in the columns")
   4304 
   4305         if inplace:

KeyError: "None of ['PGM_SYS_ID'] are in the columns"
```

**Comment by shansen5** [comment]
Working on this in the 'bug-fixes' branch.
