### ISSUE TITLE
Add GHG data

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#34]
We should add GHG reporting data. It is accessible within the ECHO_EXPORTER table as well as the new Air Emissions table.

It will help us move forward on this: https://github.com/edgi-govdata-archiving/Environmental-Enforcement-Watch/issues/28

**Comment by shansen5** [comment]
The POLL_RPT_COMBINED_EMISSIONS table contains 4 types of data, which is identified in the PGM_SYS_ACRNM field.
        EIS - Emission Inventory System - National Emissions Inventory
        E-GGRT - Greenhouse Gas Reporting Program
        TRIS - Toxics Release Inventory System
        CAMDBS - Clean Air Markets Division Business System
I am using a custom SQL query to get just the E-GGRT records for Greenhous Gases, TRIS for Toxic Releases and all records for the Combined Air Emissions.

ECHO_EXPORTER has a GHG_IDS field that I can't make sense of.  The GHG data, in POLL_RPT_COMBINED_EMISSIONS, has a REGISTRY_ID which can be used to match with ECHO_EXPORTER's REGISTRY_ID.  So far I've only ever seen one value in GHG_IDS, and it is not a format of other IDs.  I am ignoring it, but curious.
