### ISSUE TITLE
Add export of facility lat/lons

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#35]
This information is available in ECHO_EXPORTER. It will help us create custom maps for the reports (see draft template: https://www.canva.com/design/DAD8DeOt_ds/G8Gl4K9XdLUlBrGO_-UhOw/edit#4)

**Comment by ericnost** [comment]
Ideally, we'd be able to export lat/lons with each dataset (e.g. CWA violations in a Congressional District), but that would require a join with ECHO_EXPORTER. 

At the very least, we can allow exporting the ECHO_EXPORTER data for the specified geography.

**Comment by ericnost** [comment]
@calderEDJ Just letting you know that we are working on making it possible to actually export the geographic information from the notebooks so that it's possible to make custom maps for the reports (filling the "Map goes here" hold in your awesome template)

**Comment by shansen5** [comment]
@ericnost The bug-fixes branch that I'm ready to merge includes a new cell for exporting the ECHO_EXPORTER data for the facilities in the region.  I'll work on merging the lat/lon from facilities into the program data in a separate branch.
