### ISSUE TITLE
Find a better way to get the state's congressional districts

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO-Cross-Program#43]
When a user wants to look at a report by CD we have to ask the state and then the CD in the state.  Currently, to list the CDs in the chosen state in a dropdown list we are querying the entire ECHO_EXPORTER table for unique FAC_DERIVED_CD113 values.  That is a time-consuming operation, for something that doesn't change.

We may soon be querying a census.gov API for demographic information, so getting the CD list from there is one possibility.  It is probably simpler to just have our own table, either in the Stonybrook DB or a local file that has two fields--1) two character state abbreviation, 2) CSV string of CDs in the state.

**Comment by ericnost** [comment]
@shansen5 - I just came across this project, which may offer us a quick way to access information about Congressional Districts and their geographic data:

https://github.com/unitedstates/districts

For instance, here is a JSON of all the districts from 2012 (I think this counts for the 113th Congress.) https://api.github.com/repos/unitedstates/districts/contents/cds/2012

I think this could be easily processed to separate state and CD number into a new table.

And here is the GeoJSON for NY-1: https://theunitedstates.io/districts/cds/2012/NY-1/shape.geojson

This would make adding the outline of CDs to our maps hopefully much easier.

**Comment by shansen5** [comment]
I like the approach of using the geojson for the districts.  I think I'll take it in two steps (two branches).  First just get the list of CDs and counties read from CSV in the ECHO_modules.  Then get the CD (and county) shapes into the maps.
