### ISSUE TITLE
Move creation of the instances of DataSet into an external python file.

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO-Cross-Program#46]
Decide whether this goes:
- in ECHO-modules/DataSet.py, with the definition of the class.
- in ECHO-modules as a separate .py file.
- in ECHO-Cross-Program as a separate .py file.

**Comment by ericnost** [comment]
This is a good idea, and a good question. My inclination is to say: "in ECHO-Cross-Program as a separate .py file" I think we will want to use it again for other repos/notebooks, like the Sunrise notebook, but the datasets we need to pull there will be different and specific to that project, so we would copy and modify for that repo. Alternatively, we could call it "Data_Cross-Program.py" or something like that and keep it in ECHO-modules. Then have "Data_Sunrise.py" and so on.
