### ISSUE TITLE
Move creation of data sets into a make_data_sets.py file in the repository.

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO-Cross-Program#51]
Creation of the data sets (objects of the DataSet class defined in ECHO_modules/DataSet.py) are a large block of code, imposing to the non-programmer and interfering with the flow of the notebook.  They can be moved to an external file in this repository, make_data_sets.py.

Note that the name of the shared repository had to be renamed from ECHO-modules to ECHO_modules, since Python will not allow a '-' in the name of a module.

**Comment by ericnost** [comment]
Sounds good! Closes #46
