### ISSUE TITLE
Make charts pretty

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#52]
@Frijol made some very helpful changes to the charts in the COVID notebook here: https://github.com/edgi-govdata-archiving/ECHO-COVID19 Look in particular at the `def charter()` code block and the block with the visualization parameters. This is quite the step up from our default charts and we should try to adopt it in this notebook.

Related to #48

**Comment by shansen5** [comment]
We can make the charter() and mapper() functions from the COVID-19 repository general cross-notebook utilities, move them into ECHO_modules, and re-use them here.

**Comment by ericnost** [comment]
That's a good idea!
