### ISSUE TITLE
Combined Air Emissions and Greenhouse Gases are not working again

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO-Cross-Program#57]
I suspect this is an issue with the float/string type of REGISTRY_IDs again.

**Comment by ericnost** [comment]
Shoot. I've had some luck with this in the `get_data` function:

```
if (index_field == "REGISTRY_ID"):
        ds = pd.read_csv(data_location,encoding='iso-8859-1', dtype={"REGISTRY_ID": "Int64"})
```

I suppose we could just remove the `if` and always treat REGISTRY_ID as an integer. 

Actually, I think we could treat it as a string or float, so long as it's consistently treated that way. The problem right now I think is that when we load the Air Emissions table, Registry ID is one type, and when we load ECHO_EXPORTER it's another type, and so we can't join records across the two tables.
