### ISSUE TITLE
Let's use semantic markdown

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#8]
Let's use semantic markdown, bullet points like * rather than `<li>`

_Originally posted by @Frijol in https://github.com/edgi-govdata-archiving/ECHO-Cross-Program/pull/6_

**Comment by Frijol** [comment]
Was this meant to close, or should we apply more broadly across notebooks?

**Comment by ericnost** [comment]
Meant to close. I think we should apply more broadly across notebooks, but can include that in an issue in the EEW repo?
