### ISSUE TITLE
Fix write_file in CrossProgram.ipynb

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#86]
The write_file function in 
```
write_file( df=fac_pgm_data, base=program.name+'-'+fac_widget.value, 
               type=region_type_widget.value, state=state_name, region=region_selected )
```
is not found. Perhaps it was replaced with something else in utilities.py?

**Comment by shansen5** [comment]
It was changed to write_dataset() in utilities.py, and was correctly changed in cell 9 but not in cell 13.
