### ISSUE TITLE
Change Air Violations calculation in AllPrograms

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Cross-Program#87]
Currently we group CAA violations data by HPV_DAYZERO_DATE This has the effect of only showing High Priority Violations and not also Federally Reportable Violations. I am assuming that when we call the server, we are not asking it to return data based on a date - instead, we filter by date at some other point. Could we, at the point where we filter by date, do the following? `air_violations["Date"] = air_violations["EARLIEST_FRV_DETERM_DATE"].fillna(air_violations["HPV_DAYZERO_DATE"])` , so that we have one date column that includes both HPVs and FRVs? That line creates a new column "Date" that merges FRV dates with HPV dates, so that we only have one column to work with. This would also require changing the date column property in make_data_sets.py to "Date" instead of "HPV_DAYZERO_DATE"  so that things work when we run the groupby date function in later cells.

Does that make sense?

**Comment by shansen5** [comment]
The DataSetResult class's store() method was modified to do the required Date field modification.

```
    def store( self, df ): 
        if ( self.dataset.name == 'CAA Violations' ):
            df['Date'] = df['EARLIEST_FRV_DETERM_DATE'].fillna(
                df['HPV_DAYZERO_DATE'] )   
        self.dataframe = df

```
