### ISSUE TITLE
Remove/replace the All Facilities: 3 Years Violations & 5 Years of Inspections section

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/ECHO-Cross-Program#9]
See the comment for the full discussion:

_Originally posted by @ericnost in https://github.com/edgi-govdata-archiving/ECHO-Cross-Program/diffs_

**Comment by ericnost** [comment]
Will also remove the cross-program, individual facility charts code block that is drafted towards the end of the notebook.
