### ISSUE TITLE
Change % to Percent

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/ECHO-Cross-Program#97]
![Screen Shot 2020-09-17 at 12 05 04 PM](https://user-images.githubusercontent.com/454690/93515881-2119f980-f8de-11ea-9188-0aaad3c0d9c5.png)

At a glance, reads as "10%". Make sure it's obvious that this is a section number and not the finding.

**Comment by shansen5** [comment]
The change has been made and merged.
